### ISSUE TITLE
Array is being mangled while streaming

### ISSUE THREAD

**Issue by allain** [mimetnet/node-stream-array#2]
I just spent the better part of a half an hour hunting down a bug in a unit test that ended up being caused by the input array being mangled by this package.

Would you mind either:
1. making it shallow copy the array before mutation
2. changing the algorithm to iterate without mutation
3. documenting front and center that it mutates the input array

If you want, I'll gladly submit a pull request with #2 done if you want.

**Comment by mimetnet** [comment]
Closed in master and published to npm as v1.1.0

**Comment by mimetnet** [comment]
Closed in master and published to npm as v1.1.0
